config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  resources :products
end

app/models/color.rb
class Color < ActiveRecord::Base

  #Relacionamentos------------------------------------------------------------------------------------------------------

  has_many :product_variations

  #Validações-----------------------------------------------------------------------------------------------------------

  validates_presence_of :name, :hexadecimal

end

app/models/product.rb
class Product < ActiveRecord::Base

  #Relacionamentos------------------------------------------------------------------------------------------------------

  has_many :product_variations, dependent: :delete_all
  accepts_nested_attributes_for :product_variations, reject_if: :all_blank, allow_destroy: true



  #Validações-----------------------------------------------------------------------------------------------------------

  validates_uniqueness_of :name
  validates_presence_of   :name, :description


end

app/models/product_variation.rb
class ProductVariation < ActiveRecord::Base

  #Relacionamentos------------------------------------------------------------------------------------------------------

  belongs_to :product
  belongs_to :size
  belongs_to :color



  #Validações-----------------------------------------------------------------------------------------------------------

  validates_presence_of :quantity, :color_id, :size_id
  validates_numericality_of :quantity, :only_integer => true, :greater_than_or_equal_to => 0

  def destroy_variation
    return self.destroy!
  end
end

app/models/size.rb
class Size < ActiveRecord::Base

  #Relacionamentos------------------------------------------------------------------------------------------------------

  has_many :product_variations

  #Validações-----------------------------------------------------------------------------------------------------------

  validates_presence_of :name, :abbreviation
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @q = ProductVariation.ransack(params[:q])
    @product = @q.result.order('product_id ASC').paginate(page: params[:page], per_page: 10)
  end

  def new
    @product = Product.new
    @product.product_variations.build
    respond_to do |format|
      format.html { render :new }
      format.json { render Json: {status: :sucess, data: @product} }
    end
  end

  def edit
    @product = Product.find(params[:id])
    respond_to do |format|
      format.html { render :edit }
      format.json { render json: {status: :success, data: @product} }
    end
  end

  def create
    @product = Product.new(create_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to products_path, notice: 'Produto cadastrado com sucesso.'}
        format.json { render json: { status: :success, data: @product } }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    @product = Product.find(params[:id])
    respond_to do |format|
      if @product.update(update_params)
        format.html { redirect_to products_path, notice: 'Produto atualizado com sucesso.'}
        format.json { render json: { status: :success, data: @product } }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    status = false
    product_variation = ProductVariation.find(params[:id])
    @product = product_variation.product
    if (@product.product_variations.count <= 1)
      status = @product.destroy
    else
      status = product_variation.destroy_variation
    end
    respond_to do |format|
      if status
        format.html { redirect_to products_path, notice: 'Produto deletado com sucesso.'}
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def create_params
    params.require(:product).permit(:name, :description,
      product_variations_attributes: [:id, :quantity, :size_id, :color_id, :_destroy])
  end

  def update_params
    params.require(:product).permit(:name, :description,
      product_variations_attributes: [:id, :quantity, :size_id, :color_id, :_destroy])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def sizes
    Size.all
  end

  def colors
    Color.all
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/link_to_helper.rb
module LinkToHelper

  def button_link_to(name = nil, options = nil, html_options = {}, &block)
    html_options[:class] ||= ''
    html_options[:class] = ' btn btn-primary ' + html_options[:class]
    link_to(name, options, html_options, &block)
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/index.html.erb
<div class="container">
  <div class="jumbotron">
    <h1 class="align_center">Teste Synergia!</h1>
    <h3 class="align_center">Uma aplicação simples para testar as habilidades com Ruby on Rails.</h3>
    <br>

    <div class="row">
      <div class="col-md-6">
        <h4><u>Configuração</u></h4>
        <p>O teste deve ser feito utilizando:</p>
        <ul>
          <li>Rails 4.2.0 ou maior.</li>
          <li>Ruby 2.2.0 ou maior.</li>
        </ul>
      </div>
      <div class="col-md-6">
        <h4><u>Procedimento</u></h4>
        <p>Após a leitura do enunciado crie um repositorio publico em sua conta, e ao finalizar o teste compartilhe o link no email:</p>
        <ul>
          <li>alexsandro.rocha.prs@synergiaconsultoria.com.br.</li>
        </ul>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <h4><u>Prazo de entrega</u></h4>
        <p>
          2 dias a partir do recebimento do teste por email. Mande o email com o link do repositório mesmo que não
          tenha finalizado tudo 100%, gostariamos de analisar o seu código de qualquer forma.
        </p>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <h4><u>Descrição da tarefa:</u></h4>
        <p>
          Um cliente precisa de uma aplicação para controle de estoque dos seus produtos. Ele pode ter um mesmo produto
          em diferentes tamanhos e cores.
        </p>
        <p>Por exemplo, ele pode ter no estoque:</p>
        <ul>
          <div class="row">
            <div class="col-md-4">
              <li>5 peças da Camiseta X, na cor preta, tamanho P</li>
            </div>
            <div class="col-md-4">
              <li>2 peças da Camiseta X, na cor preta, tamanho M</li>
            </div>
            <div class="col-md-4">
              <li>3 peças da Camiseta X, na cor preta, tamanho G</li>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4">
              <li>7 peças da Camiseta X, na cor azul, tamanho M</li>
            </div>
            <div class="col-md-4">
              <li>1 peça da Camiseta Y, na cor braca, tamanho M</li>
            </div>
            <div class="col-md-4">
              <li>Etc...</li>
            </div>
          </div>
        </ul>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <h4><u>O que você irá fazer:</u></h4>
        <p>
          Precisamos de uma tela onde seja possível cadastrar um produto com nome e descrição, e relacionar novas cores,
          tamanhos e quantidade *em um único formulário utilizando Nested Forms*. Após o cadastro, temos que ter uma tela onde listar
          os produtos disponíveis em cada combinação de tamanho e cor. Cor e tamanho não precisa ter CRUD,
          apenas crie os modelos e popule com alguns dados de teste para serem relacionados ao produto (Pode ser um arquivo de seed).
        </p>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <h4><u>Exemplo de banco de dados:</u></h4>
        <a  href="https://bitbucket.org/sis_synergia/teste-rails/raw/ac154f3965918b60b10b5c9e7421b5b10936e8fb/public/Teste_Synergia.png" target="_blank" role="button">https://bitbucket.org/sis_synergia/teste-rails/raw/ac154f3965918b60b10b5c9e7421b5b10936e8fb/public/Teste_Synergia.png</a>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6">
        <h4><u>Requisitos:</u></h4>
        <ul>
          <li>Escrever testes de model e controller utilizando RSpec ou MiniTest. (Nosso projeto atual usa RSpec).</li>
          <li>Não utilizar o scaffold. Mostre sua habilidade em criar views, controllers, models, sem usar scaffold.</li>
          <li>Organização e legibilidade do código.</li>
          <li>Se utilizar gems, listar quais gems foram utilizadas, e para qual finalidade.</li>
        </ul>
      </div>
      <div class="col-md-6">
        <h4><u>Bônus:</u></h4>
        <ul>
          <li>Usar bootstrap para formatar as páginas de cadastro.</li>
          <li>Utilizar SimpleForm.</li>
          <li>Utilizar Docker (docker-compose) para subir o banco com a aplicação em containers separados</li>
        </ul>
      </div>
    </div>

      <p><a class="btn btn-primary btn-lg" href="http://www.synergiaconsultoria.com.br/" target="_blank" role="button">Conheça a Synergia</a></p>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="footer-copyright text-center py-3">Gilberto F S Junior
    <a href="https://www.linkedin.com/in/gilberto-sousa-3a8aa478/" target="_blank"> Linkedin </a>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="http://www.synergiaconsultoria.com.br/" target="_blank">Synergia</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="<%= root_path %>">Teste Synergia</a></li>
        <li><a href="<%= new_product_path %>">Cadastro de Produto</a></li>
        <li><a href="<%= products_path %>">Lista de Produtos</a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ControleEstoqueSynergia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag :defaults, "nested_form" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>

<% flash.each do |msg| %>
  <%= content_tag :div, msg, class: "alert alert-info" %>
<% end %>

<%= yield %>

<%= render 'layouts/footer' %>
</body>
</html>

app/views/products/_form.html.erb
<%= nested_form_for(@product) do |f| %>

  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> Na criação do produto!</h2>
      <ul>
        <% @product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control",  placeholder: t('activerecord.attributes.product.name') %>
    </div>
    <div class="col-md-6">
      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control", placeholder: t('activerecord.attributes.product.description') %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <h4>Variações</h4>
      <small> Poderá ser relacionado quantas cores, tamanhos e quantidade há uma unica produto.</small>
    </div>
  </div>
  <br>
  <div class="row fields">
    <div class="col-md-12">
      <%= f.fields_for :product_variations do |product_variation| %>
        <%= render partial: 'product_variations', locals: {product_variation: product_variation} %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <%= f.link_to_add t('add_variation'), :product_variations, class: "btn btn-default btn-primary" %>
      <%= f.submit t('submit'), class: "btn btn-default btn-success float_right" %>
    </div>
  </div>

<% end %>

app/views/products/_form_aux.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>

    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> Erro na criação do produto!</h2>

      <ul>
        <% @product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">

    <%= f.label :name, "Name:", class: "col-md-2 control-label" %>
    <div class="col-md-4">
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <br>

  </div>

  <div class="form-group">

    <%= f.label :description, "Description:", class: "col-md-2 control-label" %>

    <div class="col-md-4">
      <%= f.text_area :description, class: "form-control" %>
    </div>

    <br>

  </div>


  <div class="form-group">

    <%= f.label :quantity, "Quantity:", class: "col-md-2 control-label" %>

    <div class="col-md-2">
      <%= f.text_field :quantity, class: "form-control" %>
    </div>

    <br>

  </div>


  <div class="form-group">

    <%= f.label :size, "Size:", class: "col-md-2 control-label" %>

    <div class="col-md-4">
      <% sizes.each do |s| %>
        <div class="col-md-4">
          <%= check_box_tag "product[size_ids][]", s.id, f.object.sizes.include?(s) %>
          <%= s.abbreviation %>
        </div>
      <% end %>
    </div>

    <br>

  </div>

  <div class="form-group">

    <%= f.label :color, "Color:", class: "col-md-2 control-label" %>

    <div class="col-md-4">
      <% colors.each do |c| %>
        <div class="col-md-4">
          <%= check_box_tag "product[color_ids][]", c.id, f.object.colors.include?(c) %>
          <%= c.name %>
        </div>
      <% end %>
    </div>

    <br>

  </div>

<!--  <div class="form-group">-->
    <%#= f.label :picture, "Picture:", class: "col-md-2 control-label" %>
<!--    <div class="col-md-6">-->
      <%#= f.file_field :picture %>
<!--    </div>-->
<!--    <br><br>-->
<!--  </div>-->

  <%= f.submit "Submit", class: "btn btn-default btn-primary" %>

<% end %>

app/views/products/_product_variations.html.erb
<% if defined?(product_variation)%>

  <div class="row m_b_15">
    <div class="col-md-3">
      <%= product_variation.label t('activerecord.attributes.product_vatiation.quantity') %>
      <%= product_variation.number_field :quantity, class: "form-control",  placeholder: t('activerecord.attributes.product_vatiation.quantity') %>
    </div>
    <div class="col-md-3">
      <%= product_variation.label t('activerecord.attributes.product_vatiation.size_id') %>
      <br>
      <%= product_variation.collection_select :size_id, sizes, :id, :abbreviation, {prompt: "Informe um tamanho"}, {class: "form-control"}%>
    </div>
    <div class="col-md-3">
      <%= product_variation.label t('activerecord.attributes.product_vatiation.color_id') %>
      <br>
      <%= product_variation.select(:color_id, colors.order('name ASC').map{|c| [t("colors.#{c.name}"), c.id] }, {prompt: "Informe uma Cor"}, {class: "form-control"} )%>
    </div>
    <div class="col-md-3 m_t_25">
      <%= product_variation.link_to_remove t('remove_variation'), class: "btn btn-default btn-warning float_right" %>
    </div>
  </div>


<% end %>

app/views/products/edit.html.erb
<div class="well container ">

  <%= simple_form_for @product, :url => {:controller => :products, action: :update}, :html => {:class => 'form-horizontal', method: :PATCH} do |product| %>

    <div style="text-align: center;" class="row">
      <h2>Editar Produto
        <br>
        <small>Informe os dados para a edição do produto!</small>
      </h2>
    </div>
    <%= render partial: 'form', locals: {product: product} %>
  <% end %>
</div>

app/views/products/index.html.erb
<div class="well container" >
  <h2><%= t('filters') %></h2>
    <%= search_form_for(@q, url: products_path , method: :get) do |f| %>

      <div class="row">

        <div class="col-md-6 m_b_15">
          <%= f.search_field :product_name_cont, placeholder: "Nome do Produto", class: "form-control" %>
        </div>

        <div class="col-md-6 m_b_15">
          <%= f.search_field :product_description_cont, placeholder: "Descrição do Produto", class: "form-control" %>
        </div>

      </div>

      <div class="row">

        <div class="col-md-6 m_b_15">
          <%= f.select(:color_id_eq,  colors.order('name ASC').map{|c| [t("colors.#{c.name}"), c.id] }, {prompt: "Informe uma Cor"}, {class: "form-control"} )%>
        </div>


        <div class="col-md-6 m_b_15">
          <%= f.collection_select(:size_id_eq, sizes.all.present? ? sizes.order('abbreviation ASC') : sizes.all, :id, :abbreviation, {prompt: "Informe um tamanho"}, {class: "form-control"})%>
        </div>

      </div>

      <div class="row" style="float: right;">

        <div class="col-md-6">
          <%= link_to '<button type="button" class="btn btn-default btn-info">Limpar</button>'.html_safe, products_path %>
        </div>

        <div class="col-md-6">
          <%= f.submit t('filtar'), class: "btn btn-default btn-success float_right" %>
        </div>
      </div>

    <% end %>

</div>

<div class="well container" >
  <div class="row align_center">
    <h2><%= t('activerecord.models.products') %></h2>
    <ul class="list-inline">
      <li>
        <a href="<%= new_product_path %>">
          <i class="glyphicon glyphicon-plus"> Cadastrar novo produto</i>
        </a>
      </li>
    </ul>
  </div>

  <% if @product.present? %>
    <%= will_paginate @product %>
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Nome</th>
        <th>Descrição</th>
        <th>Cor</th>
        <th>Tamanho</th>
        <th>Quantidade</th>

        <th>Ações</th>
      </tr>
      </thead>
      <tbody>
      <% @product.each do |product_variation| %>
        <tr>
          <td>
            <%= product_variation.product.name%>
          </td>
          <td>
            <%= product_variation.product.description%>
          </td>
          <td>
            <%= t("colors.#{product_variation.color.name}") %>
          </td>
          <td>
            <%= product_variation.size.abbreviation%>
          </td>
          <td>
            <%= product_variation.quantity%>
          </td>
          <td>

            <%= button_link_to '', edit_product_path(product_variation.product), class: 'glyphicon glyphicon-pencil', title: "Editar" %>
            <%= button_link_to '', product_path(product_variation.id),      class: 'glyphicon glyphicon-trash', title: "Excluir", method: :delete, data: { confirm: 'Tem certeza que quer deletar o produto?' } %>
          </td>
      <% end %>
      </tr>
      </tbody>
    </table>
    <%= will_paginate @product %>
  <% else %>
    <div class="well container " style="width: 100%!important; margin-bottom: 0px!important;">
      <div class="row" style="text-align: center">
        <h2> Não Existe Produto Cadastrado! </h2>
      </div>
    </div>
  <% end %>
  
</div>

app/views/products/new.html.erb
<%= simple_form_for @product, :url => {:controller => :products, action: :create}, :html => {:class => 'form-horizontal'} do |product| %>
  <div class="well container" >
    <div class="row align_center">
      <h2>Cadastrar Novo Produto
        <br>
        <small>Informe os dados para a criação de um novo produto!</small>
      </h2>
    </div>
    <%= render partial: 'form', locals: {product: product} %>
  </div>

<% end %>